### ISSUE TITLE
change plotting and grid saving behavior

### ISSUE THREAD

**Issue by amoodie** [DeltaRCM/pyDeltaRCM#28]
## Status

Current defaults are:
```yaml
save_eta_figs: False
save_stage_figs: False
save_depth_figs: False
save_discharge_figs: False
save_velocity_figs: False
save_eta_grids: False
save_stage_grids: False
save_depth_grids: False
save_discharge_grids: True
save_velocity_grids: True
```

Additionally, figure saving is sequential, which can create a lot of files for a case-matrix with long run times.

## Ideas: 
* change defaults to only `save_eta_figs: True`. This keeps new-user startup-cost low (user can see a working run without any config), but does not clutter outputs and config files with unwanted data for others.
* wrap each of the save_fig operations into one function, just prefix with the variable name.
* make the save figure option overwrite file by default, only preserving the latest state of the model (`eta.png`). Optionally, add a config option `save_sequential_figs` as a boolean to save as sequential figures (`eta_1000.png`, `eta_1050.png`).
* remove color bar limit from `eta` plotting.

Proposed defaults:
```yaml
save_eta_figs: True
save_stage_figs: False
save_depth_figs: False
save_discharge_figs: False
save_velocity_figs: False
save_eta_grids: False
save_stage_grids: False
save_depth_grids: False
save_discharge_grids: False
save_velocity_grids: False
```
