### ISSUE TITLE
Matrix expansion in config yaml

### ISSUE THREAD

**Issue by ericbarefoot** [DeltaRCM/pyDeltaRCM#32]
Per thoughts from @amoodie:
>Additionally, this could let us do cool things like config matrix expansions where something like:
```yaml
n_timesteps: 100

matrix:
  input_sand_fraction:
    - 0.4
    - 0.8
```
> produces two runs, each run for 100 timesteps. One run has sand frac 0.4, one has 0.6, and all other parameters are at default values. This could come much later, but could be a cool feature to have.

It would be nifty to have the input configuration yaml file allow for a matrix expansion. I will make this issue and flag it as an enhancement for the future.
